### ISSUE TITLE
Word Disintegration

### ISSUE THREAD

**Issue by jaimovier** [echo-lab/live-writing-osc#10]
Is there some way of creating an effect that disintegrates the words?

**Comment by panavrin** [comment]
hm. this can be tough. Would `\distort` work? Breaking a word into each letter may be possible but breaking a letter into multiple pieces is tough as each letter is one piece (mesh). Even in the former case, I would love to know how they would move.

**Comment by jaimovier** [comment]
It would be more like the former. We tried distort.. this is more spatial.. thinking that the letters can move away from the center of the word.

**Comment by panavrin** [comment]
@jaimovier could you review this?

**Comment by jaimovier** [comment]
I couldn't get it to work. I'm sending OSC message "/disintegrate val" "/integrate val" and don't see any changes in the text... am I using it wrong? "/alpha val" works correctly

**Comment by jaimovier** [comment]
Chrome shows the following message after sending /desintegrate /integrate "removed requires 4 more parameters"

**Comment by panavrin** [comment]
Did you try the examples in pure data file?

/disintegrate 0 0 0 3

Make sure that you have bunch of text before you try.

**Comment by jaimovier** [comment]
got it! thanks
