### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by jaimovier** [echo-lab/live-writing-osc#6]
The system doesn't seem to recognize special characters via OSC, such as \n \b or specially for spanish characters \'i \'o that are needed for "Seducción" or "Sílabas"

**Comment by panavrin** [comment]
so what is the osc messages sent when special characters are sent?

**Comment by jaimovier** [comment]
It can be adjusted. For now, I tried \n for new line or \b for backspace. We also need to send accent marks (e.g. á é í ó ú)

**Comment by jaimovier** [comment]
An initial table of characters between OSC and Server:
```
IN --> OUT
\'a --> á
\'e --> é
\'i --> í
\'o --> ó
\'u --> ú
\'n --> ñ
```

this should be the same for lower and upper case (e.g. \'A --> Á)

Other commands:
```
\n --> new line
\b --> backspace
```

**Comment by panavrin** [comment]
@jaimovier Could you test the accented characters with the following message? 


you have to use the double backslash. 

/add \\'a\\'e\\'o\\'i\\'u\\'n\\'A\\'E\\'I\\'O\\'U\\'N

**Comment by panavrin** [comment]
Also please test linebreak. 

It should have a double backslash 

/add test\\ntest

**Comment by jaimovier** [comment]
works great!

In Max/MSP, for some reason you need to use double backslashes as it deletes a single backslash internally (e.g. instead of "\'a" you need to use "\\'a")

**Comment by panavrin** [comment]
Please close the issue if you think it's done. Thanks!
